name: cDuello
version: '${project.version}'
main: dev.itscactus.cduello.Main
api-version: '1.21.4'
description: Gelişmiş düello eklentisi
authors: [itscactusdev]
website: https://itscactus.dev

commands:
  duello:
    description: Düello komutları
    usage: /duello <oyuncu> [bahis]
    aliases: [duel, vs, duelloarena]

permissions:
  cduello.player:
    description: Oyuncu izinleri
    default: true
    children:
      cduello.duel: true
      cduello.stats: true
  cduello.admin:
    description: Admin izinleri
    default: op
    children:
      cduello.player: true
      cduello.reload: true
      cduello.arena: true 