name: cDuello
version: 1.0.0
main: dev.itscactus.cduello.Main
api-version: 1.21.4
author: itscactusdev
description: Gelişmiş bir düello eklentisi
depend: [Vault]
softdepend: [PlaceholderAPI]

commands:
  duello:
    description: Düello komutları
    usage: /duello <oyuncu|kabul|reddet|iptal|çık|sıralama>
    aliases: [duel]
  dueladmin:
    description: Düello yönetim komutları
    usage: /dueladmin <reload|arena|stats>
    permission: cduello.admin

permissions:
  cduello.admin:
    description: Düello eklentisinin yönetim komutlarına erişim sağlar
    default: op
  cduello.use:
    description: Temel düello komutlarını kullanma izni
    default: true 